### ISSUE TITLE
No Duff-Porter Composite section for method Replace

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/Usage#6]
### ImageMagick version

7.1.1.39

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

At https://usage.imagemagick.org/compose, it list a method for Duff-Porter composition of Replace.  It is a dead link and I can not find a section for it in the docs on that page

### Steps to Reproduce

click the link - it is dead.

### Images

none

**Comment by dlemstra** [comment]
Thanks for reporting this Fred. Next time please open an issue in this repository instead. I have removed that link because it looks like `Copy` does the same as `Replace`.

**Comment by fmw42** [comment]
Not sure about “repository”?  What is that and what did I do?  I just posted to the GIT forum for IM 7, I thought.  Is that not the correct place?

Fred

**Comment by dlemstra** [comment]
The source of the Usage site is this repository: https://github.com/ImageMagick/Usage

**Comment by fmw42** [comment]
I did not know about that site.  How do I know when to use that rather than the other that I had used?

Can you cross-link all the different sites or is there already a main page?

Fred

**Comment by dlemstra** [comment]
If you report something about the usage site then use this repository. The code for the Usage and "normal" Website are hosted in a separate GitHub repository so it would be better to report issues about them in the appropriate repository,

p.s. You seem to be responding to auto generated emails instead of visiting the site. If you visit this repository it will probably be more clear what is happening.
